### ISSUE TITLE
Enter key doesn't work in Google Keep

### ISSUE THREAD

**Issue by alandoyle** [VladThodo/behe-keyboard#6]
The keyboard works really well in all apps except the Enter key doesn't work in Google Keep.
If you press Enter to create a new line the cursor disappears and no new line is created.
You then need to click on the text area to continue typing.
Really bizarre.

**Comment by VladThodo** [comment]
I have experienced the issue myself. Unfortunately  , I'm really confused about it. I need to perform somea additional tests to be able to understand what's happening. I'll try to fix this as fast as posible. Thanks for your feedback!

**Comment by VladThodo** [comment]
I have experienced the issue myslef. Unfortunately, I'm a bit confused about it. I need to perform some additional tests to understand what's happening. I'll fix it as soon as I can. Thanks for your feedback!

**Comment by aozkesek** [comment]
Hi Vlad, first thanks to great keyboard app.  

Google notes, Google inbox has same problem.  I can not go through the new line in there.

but, as you see with this comment, and multiline textbox, enter key works as expected, make new line.

i was thinking that clone and debug the app, but i  am sure you will do best.

**Comment by VladThodo** [comment]
I have done a bit of research, but still can't understand why the text fields don't process the hard enter key code. However, I was able to fix it with the help of some code from the SampleSoftKeyboard example provided in the android SDK. The fix will be available in the next update.

**Comment by alandoyle** [comment]
Fantastic. Can't wait to try it out. Thank you for finding and fixing it so fast :)

**Comment by letkan** [comment]
I've had a similar experience with enter key in a notebook, it would just hide the keyboard and the cursor would stay in the same place. Related, the numerical pad for entering the pin code doesn't have enter or confirm key so it can't be used.

**Comment by VladThodo** [comment]
That's a big fault of mine. I literally forgot to add the enter key to the layout. I can't understand how it happened, but thanks for telling me. I was not aware about that at all. I'm going to add an enter key to the numerical keyboard also. Thanks!

**Comment by aozkesek** [comment]
Google Keep and Inbox are both good now.  

Vlad, thanks again.

**Comment by VladThodo** [comment]
I pushed another update today that also fixes the rest of the enter keys. It was late at night when I added the update yesterday and I forgot to change the enter key code for the other layouts (symbols, arrows, etc.). Now it works. I also added an enter key to the numbers layout. 

@alandoyle, I think we can declare this fixed.

**Comment by aozkesek** [comment]
Hi Vlad,

i want to share one of my experience with enter - return key at numbers layout.

the case is,

a. open firefox,
b. enter an url
c. switch the numbers layout
d. then hit enter key.

i saw a strange object at end of the url, and page go nowhere. so enter key of numbers layout does not trigger the navigate action.

i think you maybe fixed this already todays update.

**Comment by VladThodo** [comment]
Yeah, I experienced that issue. It's fixed now.

**Comment by letkan** [comment]
I'll build it later on see how it goes. Thanks

**Comment by alandoyle** [comment]
Just got the latest update and it works perfectly. Thank you :)

**Comment by cpmv** [comment]
I am still experiencing this issue in apps like Facebook Messenger, Telegram, Google Inbox, ...

**Comment by danehrlich1** [comment]
Still seeing this as well
